#!/bin/bash
echo "ПРОВЕРКА ПРОЕКТА"
echo "================"
echo ""
echo "1. Проверка структуры:"
ls -la | grep -E "users|posts|comments|messages_app|subscriptions|startup_packs|notifications|venv|manage.py|.env|db.sqlite3|create_data.py"
echo ""
echo "2. Проверка настроек:"
ls -la social_network/ | grep -E "settings.py|urls.py"
echo ""
echo "3. Проверка миграций:"
ls -la users/migrations/ | grep "0001"
echo ""
echo "4. Проверка суперпользователя:"
python manage.py shell -c "from users.models import User; print('Admin exists:', User.objects.filter(is_superuser=True).exists())"
echo ""
echo "ПРОВЕРКА ЗАВЕРШЕНА!"
