# Generated by Django 5.0.6 on 2026-06-25 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experts', models.ManyToManyField(limit_choices_to={'is_expert': True}, related_name='packs', to=settings.AUTH_USER_MODEL, verbose_name='Эксперты')),
            ],
            options={
                'verbose_name': 'Стартовый набор',
                'verbose_name_plural': 'Стартовые наборы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStartupPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_startup_packs', to='startup_packs.startuppack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка на стартовый набор',
                'verbose_name_plural': 'Подписки на стартовые наборы',
                'ordering': ['-subscribed_at'],
                'unique_together': {('user', 'pack')},
            },
        ),
    ]
