# Generated by Django 5.0.6 on 2026-06-27 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_packs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='startuppack',
            name='experts',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_expert': True}, related_name='packs', to=settings.AUTH_USER_MODEL, verbose_name='Эксперты'),
        ),
    ]
