# Generated by Django 5.0.6 on 2026-06-27 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_packs', '0002_alter_startuppack_experts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('source_name', models.CharField(max_length=100, verbose_name='Источник')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='Создано AI')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_posts', to='startup_packs.startuppack')),
            ],
            options={
                'verbose_name': 'Пост из RSS',
                'verbose_name_plural': 'Посты из RSS',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='StartupPackSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название источника')),
                ('rss_url', models.URLField(verbose_name='RSS-лента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_fetched', models.DateTimeField(blank=True, null=True, verbose_name='Последний сбор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='startup_packs.startuppack')),
            ],
            options={
                'verbose_name': 'Источник RSS',
                'verbose_name_plural': 'Источники RSS',
            },
        ),
    ]
